const colors: Array<{ desc: string, color: string }> = [
  { color: 'auto', desc: 'auto' },
  { color: '#FFF', desc: 'classical white' },
  { color: '#A00', desc: 'Lily Red' },
  { color: '#e91e63', desc: 'Margatroid Magenta' },
  { color: '#222', desc: 'Breathy Darkness' },
  { color: '#ef5350', desc: 'Red' },
  { color: '#ab47bc', desc: 'Purple' },
  { color: '#7e57c2', desc: 'Deep Purple' },
  { color: '#3f51b5', desc: 'Indigo' },
  { color: '#2196f3', desc: 'Blue' },
  { color: '#03a9f4', desc: 'Light Blue' },
  { color: '#00bcd4', desc: 'Cyan' },
  { color: '#009688', desc: 'Teal' },
  { color: '#4caf50', desc: 'Green' },
  { color: '#7cb342', desc: 'Light Green' },
  { color: '#c0ca33', desc: 'Lime' },
  { color: '#f9a825', desc: 'Yellow' },
  { color: '#ffa000', desc: 'Amber' },
  { color: '#fb8c00', desc: 'Orange' },
  { color: '#ff7043', desc: 'Deep Orange' },
  { color: '#795548', desc: 'Brown' },
  { color: '#757575', desc: 'Grey' },
  { color: '#546e7a', desc: 'Blue Grey' },
]
export default colors
